# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ staging ]


jobs:
  trigger_staging:
    name: Call API Vercel
    runs-on: macos-10.15
    steps:
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.STAGING_VERCEL_KEY }}
    - name: Call Staging
      run: |
        curl "$SUPER_SECRET"
